site_name: tunerc document  # 你的帮助中心名称
site_url: https://document.tunerc.com

theme:
  name: material
  language: en  # 设置界面语言为英语 (按钮、搜索提示等将显示为英文)
  logo: assets/font-black.svg  # 注意这里不需要写 docs/，MkDocs 会自动从 docs 目录开始找
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs              # 顶部大类导航栏
    - navigation.sections          # 侧边栏分段显示
    - navigation.expand            # 默认展开左侧菜单
    - navigation.top               # 滚动到顶部按钮
    - search.suggest               # 搜索自动补全建议
    - search.highlight             # 搜索结果高亮显示
    - content.code.copy            # 代码块一键复制按钮

# 导航栏配置（请根据你在 docs 文件夹下的文件名进行修改）
nav:
  - Home: index.md
  - Flight control:
      - Poly V1.2: Flight-control/tunerc-tr-fc-f05b.md
      - EZ3: Flight-control/tunerc-tr-fc-f06b.md
  - Accessories:
      - Mag&Baro Module: Accessories/tunerc-tr-pe-0001.md
  - FAQ: faq.md

# 插件配置
plugins:
  - search # 必须保留，提供搜索功能
